import Russia from './Images/Russia.png';
import Nordwind from './Images/Nordwind.png';

import Redwings from './Images/Redwings.png';
import Fly from './Images/Fly.png';

export const TICKETS_INFO = [
  {
    airlinesCompanyImg: Russia,
    ticketPrice: '7712р',
    buyOn: 'Clickavia',
    timeCityDeparture: '00:05',
    nameCityDeparture: 'Москва',
    dateCityDeparture: '24 фев 2018, Сб',
    timeCityArrival: '03:05',
    nameCityArrival: 'Барселона',
    dateCityArrival: '24 фев 2018, Сб',
    timeFlight: '5ч',
    categoryTicket: '',
    Transplantation: {
      noTransplantation: '7 712 р',
      oneTransplantation: '11 150 р',
      twoTransplantation: '16 821 р',
      threeTransplantation: '23 986 р',
    },
  },
  {
    airlinesCompanyImg: Nordwind,
    ticketPrice: '7712р',
    buyOn: 'Clickavia',
    timeCityDeparture: '00:15',
    nameCityDeparture: 'Москва',
    dateCityDeparture: '24 фев 2018, Сб',
    timeCityArrival: '03:10',
    nameCityArrival: 'Барселона',
    dateCityArrival: '24 фев 2018, Сб',
    timeFlight: '4ч 55м',
    categoryTicket: '',
  },  {
    airlinesCompanyImg: Russia,
    ticketPrice: '7712р',
    buyOn: 'Clickavia',
    timeCityDeparture: '00:05',
    nameCityDeparture: 'Москва',
    dateCityDeparture: '24 фев 2018, Сб',
    timeCityArrival: '03:05',
    nameCityArrival: 'Барселона',
    dateCityArrival: '24 фев 2018, Сб',
    timeFlight: '5ч',
    categoryTicket: '',
  },  {
    airlinesCompanyImg: Redwings,
    ticketPrice: '7712р',
    buyOn: 'Clickavia',
    timeCityDeparture: '00:05',
    nameCityDeparture: 'Москва',
    dateCityDeparture: '24 фев 2018, Сб',
    timeCityArrival: '03:05',
    nameCityArrival: 'Барселона',
    dateCityArrival: '24 фев 2018, Сб',
    timeFlight: '5ч',
    categoryTicket: '',
  },
  {
    airlinesCompanyImg: Russia,
    ticketPrice: '7712р',
    buyOn: 'Clickavia',
    timeCityDeparture: '00:05',
    nameCityDeparture: 'Москва',
    dateCityDeparture: '24 фев 2018, Сб',
    timeCityArrival: '03:05',
    nameCityArrival: 'Барселона',
    dateCityArrival: '24 фев 2018, Сб',
    timeFlight: '5ч',
    categoryTicket: '',
  },
  {
    airlinesCompanyImg: Fly,
    ticketPrice: '7712р',
    buyOn: 'Clickavia',
    timeCityDeparture: '00:05',
    nameCityDeparture: 'Москва',
    dateCityDeparture: '24 фев 2018, Сб',
    timeCityArrival: '03:05',
    nameCityArrival: 'Барселона',
    dateCityArrival: '24 фев 2018, Сб',
    timeFlight: '5ч',
    categoryTicket: '',
  },
  {
    airlinesCompanyImg: Russia,
    ticketPrice: '7712р',
    buyOn: 'Clickavia',
    timeCityDeparture: '00:05',
    nameCityDeparture: 'Москва',
    dateCityDeparture: '24 фев 2018, Сб',
    timeCityArrival: '03:05',
    nameCityArrival: 'Барселона',
    dateCityArrival: '24 фев 2018, Сб',
    timeFlight: '5ч',
    categoryTicket: '',
  },
  {
    airlinesCompanyImg: Russia,
    ticketPrice: '7712р',
    buyOn: 'Clickavia',
    timeCityDeparture: '00:05',
    nameCityDeparture: 'Москва',
    dateCityDeparture: '24 фев 2018, Сб',
    timeCityArrival: '03:05',
    nameCityArrival: 'Барселона',
    dateCityArrival: '24 фев 2018, Сб',
    timeFlight: '5ч',
    categoryTicket: '',
  },
];